service: rest-monopoly-lambda

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  environment:
    DYNAMODB_GAME_TABLE: ${self:service}-${opt:stage, self:provider.stage}-Games

functions:
  gamesCreate:
    handler: src/main/handlers/games/create.create
    events:
      - http:
          path: '/games'
          method: post

resources:
  Resources:
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${opt:stage, self:provider.stage}-Games
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
